[package]
name = "string_calc"
version = "0.2.0"
edition = "2021"
description = "Perform calculations based on String to avoid floating point errors."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
